# version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=safe_land_user
      - POSTGRES_PASSWORD=safe_land_password
      - POSTGRES_DB=safe_land_db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: